# Generated by Django 5.2.6 on 2025-09-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='featured_product',
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.product'),
        ),
    ]
